CREATE DEFINER=`ist176180`@`%` PROCEDURE `Initialize`()
BEGIN
	DROP TABLE IF EXISTS `MemberList` CASCADE;
	DROP TABLE IF EXISTS `GroupList` CASCADE;
	
    CREATE TABLE `MemberList`
(`CHAR_name` VARCHAR(255) NOT NULL,
 `CHAR_class` VARCHAR(255) NULL,
 `CHAR_race` VARCHAR(255) NULL,
 `CHAR_AP` INT NULL,
 `CHAR_role` VARCHAR(255) NULL,
 `CHAR_level` INT NULL,	
 `CHAR_prof1` VARCHAR(255) NULL,	
 `CHAR_prof2` VARCHAR(255) NULL,
 `CHAR_GS` INT NULL);
 
 CREATE TABLE `GroupList`
(`CHAR_name` VARCHAR(255) NOT NULL,
 `CHAR_class` VARCHAR(255) NULL,
 `CHAR_race` VARCHAR(255) NULL,
 `CHAR_AP` INT NULL,
 `CHAR_role` VARCHAR(255) NULL,
 `CHAR_level` INT NULL,	
 `CHAR_prof1` VARCHAR(255) NULL,	
 `CHAR_prof2` VARCHAR(255) NULL,
 `CHAR_GS` INT NULL);
 
INSERT INTO MemberList
SELECT * FROM CHARACTERS;
 
SELECT CHAR_name, CHAR_race, CHAR_class, CHAR_role, CHAR_GS
FROM MemberList;

END